### ISSUE TITLE
Weights

### ISSUE THREAD

**Issue by zhangky666** [tteepe/EarlyBird#1]
Hello! Thank you for your excellent paper!

In my reproduction, the code "resnet = torchvision.models.resnet18(weights=torchvision.models.ResNet18_Weights.DEFAULT)" is reporting error "AttributeError: module ' AttributeError: module ' torchvision.models' has no attribute 'ResNet18_Weights'", it was solved by changing it to "resnet = torchvision.models.resnet18(pretrained=True)".

After training, run "python main.py test -c model_weights/config.yaml --ckpt model_weights/model-epoch=35-val_loss=6.50.ckpt" command, I got error "error: Parser key "config": File does not exist: '/ home/zhangkeyu/EarlyBird/EarlyBird/model_weights/config.yaml'".
Is there any file missing? Or what should I do?

I hope to reply as soon as possible, this is very important to me, thanks!

Translated with DeepL.com (free version)

**Comment by tteepe** [comment]
Hi,

you also need to change the parameters config (`-c`) and checkpoint (`-ckpt`) to the respective files created during training. You'll probably find them under `lightning_logs/version_X`.

Cheers,
Torben
